name: Ejecutando Tests # El nombre no importa, es un string

# Cada cuando quiero que se ejecute este workflow
on:
  push:
    branches: ['develop'] # Es el nombre de las ramas
  # Ejecute cada cierta cantidad de tiempo
  # schedule:
  # - cron: '0 0 * * *' # Cada día a la medianoche UTC
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs: # se pueden definir n cantidad de jobs
  test: # El nombre no importa
    runs-on: ubuntu-latest # El runner o ambiente en el que se va a ejecutar
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js v20 # El nombre es un string
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Este comando no es necesario que exista en el package.json, es uso exclusivo de CI

      - name: Run unit tests
        run: npm run test # Este comando debe existir en el package.json

  lint:
    # needs: [test] Se ejecuta una despues de la otra con este comando
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js v20 # El nombre es un string
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Este comando no es necesario que exista en el package.json, es uso exclusivo de CI

      - name: Run lint
        run: npm run lint # Este comando debe existir en el package.json
